package vm

import (
	"context"

	"github.com/gofrs/uuid"
	"github.com/spf13/cobra"

	"github.com/vatesfr/xenorchestra-go-sdk/pkg/services/library"
)

const flagName = "name"

func newSnapshotCommand() *cobra.Command {
	var name string

	cmd := &cobra.Command{
		Use:   "snapshot <id>",
		Short: "Take a snapshot of a virtual machine",
		Long: `Take a snapshot of a virtual machine.

The VM is referenced by its UUID, as returned by 'xo vm list'. Use --name to
give the snapshot a label; if omitted, Xen Orchestra generates a default name.

Examples:
  xo vm snapshot 550e8400-e29b-41d4-a716-446655440001
  xo vm snapshot <id> --name before-upgrade`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runAction(cmd, actionSpec{
				verb: "snapshot",
				id:   args[0],
				perform: func(ctx context.Context, xo library.Library, id uuid.UUID) (string, error) {
					return xo.VM().Snapshot(ctx, id, name)
				},
			})
		},
	}

	cmd.Flags().StringVar(&name, flagName, "", "label for the snapshot (default: generated by Xen Orchestra)")
	addWaitFlag(cmd)
	return cmd
}
